# Generated by Django 3.1 on 2022-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20221128_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfica',
            name='dni',
            field=models.BigIntegerField(),
        ),
    ]
