# Generated by Django 3.1 on 2022-11-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20221128_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfica',
            name='dni',
            field=models.BigIntegerField(unique=True),
        ),
    ]
