# Generated by Django 3.1 on 2022-11-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20221128_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFICAMysql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dni', models.BigIntegerField()),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('es_docente', models.BooleanField(default=False)),
                ('es_nodo', models.BooleanField(default=False)),
            ],
        ),
    ]
