# Generated by Django 3.1 on 2022-11-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personalficamysql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalfica',
            name='mail2',
        ),
    ]
