# Generated by Django 3.1 on 2022-12-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20221205_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargopersonafcejs',
            name='area',
        ),
        migrations.RemoveField(
            model_name='cargopersonafcejs',
            name='caracter',
        ),
        migrations.RemoveField(
            model_name='cargopersonafcejs',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='cargopersonafcejs',
            name='dedicacion',
        ),
        migrations.RemoveField(
            model_name='cargopersonafcejs',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='cargopersonafcejs',
            name='personal',
        ),
        migrations.DeleteModel(
            name='PersonalFICAMysql',
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellido']},
        ),
        migrations.DeleteModel(
            name='AreaFcejs',
        ),
        migrations.DeleteModel(
            name='Caracter',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='CargoPersonaFCEJS',
        ),
        migrations.DeleteModel(
            name='Dedicacion',
        ),
        migrations.DeleteModel(
            name='DepartamentoFCEJS',
        ),
        migrations.DeleteModel(
            name='PersonalFCEJS',
        ),
    ]
