# Generated by Django 3.1 on 2022-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20221227_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='es_docente',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='es_fcejs',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='es_fica',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='es_nodo',
        ),
        migrations.AddField(
            model_name='personal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
