# Generated by Django 3.1 on 2022-11-14 12:27

import dati_taller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dati_taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeservicioadomicilio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=dati_taller.models.OrdenDeServicioADomicilio.image_path, verbose_name='Imagen de referencia'),
        ),
    ]
