# Generated by Django 3.1 on 2022-11-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dati_taller', '0002_ordendeservicioadomicilio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolucionAMotivoOrdenEnTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.CharField(max_length=150)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dati_taller.motivosordenesentaller', verbose_name='Motivo relacionado con la solucion')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionAMotivoOrdenEnDomicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.CharField(max_length=150)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dati_taller.motivosordenesendomicilio', verbose_name='Motivo relacionado con la solucion')),
            ],
        ),
        migrations.AddField(
            model_name='ordendeservicioadomicilio',
            name='solucion_implementada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dati_taller.solucionamotivoordenendomicilio', verbose_name='Solucion Implementada'),
        ),
        migrations.AddField(
            model_name='ordendeservicioentaller',
            name='solucion_implementada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dati_taller.solucionamotivoordenentaller', verbose_name='Solucion Implementada'),
        ),
    ]
