# Generated by Django 3.1 on 2022-11-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dati_taller', '0003_auto_20221116_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosOrdenesEnAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Motivo de orden en domicilio',
                'verbose_name_plural': 'Motivos de ordenes en domicilio',
            },
        ),
        migrations.CreateModel(
            name='SolucionAMotivoOrdenEnAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.CharField(max_length=150)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dati_taller.motivosordenesenaula', verbose_name='Motivo relacionado con la solucion en Aula')),
            ],
        ),
        migrations.AddField(
            model_name='ordendeservicioenaula',
            name='solucion_implementada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dati_taller.solucionamotivoordenenaula'),
        ),
        migrations.AlterField(
            model_name='ordendeservicioenaula',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dati_taller.motivosordenesenaula', verbose_name='Motivo de la visita'),
        ),
    ]
