# Generated by Django 3.1 on 2022-12-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20221205_0657'),
        ('dati_taller', '0005_auto_20221122_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='ordendeservicioadomicilio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='ordendeservicioentaller',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal', verbose_name='Cliente'),
        ),
    ]
