# Generated by Django 3.1 on 2022-12-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20221227_1118'),
        ('dati_taller', '0006_auto_20221205_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
    ]
